#!/bin/bash
# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.


CURRENT_PATH="$(dirname "$(realpath "$0")")"
VENV_PATH=$CURRENT_PATH/../../.venv
PACKAGE_TO_IMPORT="yaml, requests"
PACKAGE_TO_INSTALL="PyYAML requests"
USE_VENV=false

check_requirements_or_install_if_missing() {
  python3 -c "import $PACKAGE_TO_IMPORT"
  if [ $? -eq 0 ]; then
      echo "All requirements installed"
  else
      echo "Some requirements are not installed"
      pip3 install $PACKAGE_TO_INSTALL
      if [ $? -eq 0 ]; then
          echo "All requirements installed successfully"
      else
          echo "Some requirements installation failed, please install them manually."
          exit 1
      fi
  fi
}

python3 -c "import $PACKAGE_TO_IMPORT"
if [ $? -eq 0 ]; then
    echo "All requirements installed"
else
    echo "Some requirements are not installed, try to use venv $VENV_PATH"
    USE_VENV=true
    if [ -d $VENV_PATH ]; then
        echo "venv already exists, reuse it"
    else
        echo "venv not exists, create it"
        python3 -m venv $VENV_PATH
    fi
    source $VENV_PATH/bin/activate
    check_requirements_or_install_if_missing
fi

set -e

PYTHON_PATH=$(which python3)

"$PYTHON_PATH" "$@"

if [ $USE_VENV = true ]; then
    echo "deactivate venv"
    deactivate
fi

